# .github/workflows/publish.yml
name: Publish npm Package

# Trigger only when you push a version tag (e.g., v1.0.0)
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write  # required for OIDC

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          scope: '@your-npm-scope' # optional if your package is scoped

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build  # if you have a build step, otherwise skip

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ steps.oidc-token.outputs.token }} # automatically handled by OIDC
