name: Publish to npm (Trusted Publishing)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # REQUIRED for OIDC trusted publishing

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # IMPORTANT: no NODE_AUTH_TOKEN here (OIDC will be used)
      - name: Publish to npm
        run: npm publish --access public --provenance
